### ISSUE TITLE
Request access to a single repository rather than a personal access token

### ISSUE THREAD

**Issue by jviotti** [balena-io/pensieve#142]
A personal access token means that the application has access to all the repositories the user has, and not only to the repo pensieve is meant to work with.

**Comment by LucianBuzzo** [comment]
@jviotti Without introducing some sort of backend component, there is no way around this. AFAIK GitHub do not allow you to create personal access token that can only access a single repo, though I wish the did.

**Comment by jviotti** [comment]
Closing stale issues
